services:
#  ff-testが箱の名前になってる
    ff-test:
    #buildはdockerfileのある場所教えてる contextはDockerfileのあるフォルダを
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'flyfinger'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-8000}:8000'
            - '${VITE_PORT:-5177}:${VITE_PORT:-5177}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
            - /var/www/html/node_modules
            #dbと同じ名前にすることで接続できる
        networks:
            - flyfinger_db
        depends_on:
            - mysql
    mysql:
    #基本このimage名はmysqlで問題ない
        image: 'mysql:8.3'
        ports:
            - '${FORWARD_DB_PORT:-3307}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
        # ここでflyfinger_mysqlを書いたら後からvolumesでmysqlの入ってるはこの名前考えなくていい
        # ここでデータ保存してるからdocker compose downしても消えない
            - 'flyfinger_mysql:/var/lib/mysql'
        networks:
            - flyfinger_db
            # ちゃんと動いてるか定期的に確認するするもの
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
networks:
    flyfinger_db:
        driver: bridge
        # mysqlが入ってる箱の名前
volumes:
    flyfinger_mysql:
        driver: local
